version: "3.9"

services:
  postgres:
    image: postgres:18.3
    container_name: micromarket_db
    environment:
      POSTGRES_DB: micromarket_db
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - micromarket_net
    volumes:
      - pg_data:/var/lib/postgresql

  backend:
    image: ghcr.io/bulgaria2026/micromarketapi:latest
    container_name: micromarket_be
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      DATABASE_URL: jdbc:postgresql://postgres:5432/micromarket_db
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_PUBLIC_KEY: file:/etc/secrets/jwt/app.pub
      JWT_PRIVATE_KEY: file:/etc/secrets/jwt/app.key
      CORS_ALLOWED-ORIGINS: ${CORS_ALLOWED_ORIGINS:-}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_SUCCESS_URL: ${STRIPE_SUCCESS_URL}
      STRIPE_CANCEL_URL: ${STRIPE_CANCEL_URL}
      STRIPE_SESSION_EXPIRATION_MINUTES: ${STRIPE_SESSION_EXPIRATION_MINUTES:-30}
      MAIL_ENABLED: ${MAIL_ENABLED:-true}
      RESEND_API_KEY: ${RESEND_API_KEY}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-MicroMarket}
    volumes:
      - ./secrets/jwt:/etc/secrets/jwt:ro
    depends_on:
      - postgres
    networks:
      - micromarket_net
    ports:
      - "8080:8080"  # optional if exposed via proxy

  frontend:
    image: ghcr.io/bulgaria2026/micromarketui:latest
    container_name: micromarket_ui
    environment:
      VITE_BACKEND_URL: http://backend:8080  # update when known and save in env
    depends_on:
      - backend
    networks:
      - micromarket_net
    ports:
      - "80:80"  # public entry point

networks:
  micromarket_net:
    driver: bridge

volumes:
  pg_data: