services:
  postgres:
    image: postgres:latest
    container_name: micromarket_db
    environment:
      POSTGRES_DB: micromarket_db
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
