services:
  postgres:
    image: postgres:18.3
    container_name: micromarket_db
    env_file: .env
    environment:
      POSTGRES_DB: micromarket_db
      POSTGRES_USER: ${DATABASE_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
    networks:
      - micromarket_net

  backend:
    image: ghcr.io/bulgaria2026/micromarketapi:latest
    container_name: micromarket_be
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      DATABASE_URL: jdbc:postgresql://postgres:5432/micromarket_db
      DATABASE_USERNAME: ${DATABASE_USERNAME:-admin}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-admin}
      CORS_ALLOWED-ORIGINS: http://localhost:5173
    depends_on:
      - postgres
    networks:
      - micromarket_net
    ports:
      - "8080:8080"

networks:
  micromarket_net:
    driver: bridge
