services:
  postgres:
    image: postgres:18.3
    container_name: micromarket_db
    env_file: .env
    environment:
      POSTGRES_DB: micromarket_db
      POSTGRES_USER: ${DATABASE_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
    networks:
      - micromarket_net
    ports:
      - "5432:5432"
  backend:
    image: ghcr.io/bulgaria2026/micromarketapi:latest
    container_name: micromarket_be
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      DATABASE_URL: jdbc:postgresql://postgres:5432/micromarket_db
      DATABASE_USERNAME: ${DATABASE_USERNAME:-admin}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-admin}
      CORS_ALLOWED-ORIGINS: http://localhost:5173
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_SUCCESS_URL: ${STRIPE_SUCCESS_URL:-http://localhost:5173/checkout/success?session_id={CHECKOUT_SESSION_ID}}
      STRIPE_CANCEL_URL: ${STRIPE_CANCEL_URL:-http://localhost:5173/checkout/cancel}
      STRIPE_SESSION_EXPIRATION_MINUTES: ${STRIPE_SESSION_EXPIRATION_MINUTES:-30}
      MAIL_ENABLED: ${MAIL_ENABLED:-false}
      RESEND_API_KEY: ${RESEND_API_KEY:-re_dev_dummy}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-onboarding@resend.dev}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-MicroMarket Dev}
    depends_on:
      - postgres
    networks:
      - micromarket_net
    ports:
      - "8080:8080"

networks:
  micromarket_net:
    driver: bridge
